# Generated by Django 4.1.2 on 2022-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
